# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: avikom/generic/options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='avikom/generic/options.proto',
  package='avikom.generic',
  syntax='proto3',
  serialized_options=b'Z=gitlab.ub.uni-bielefeld.de/avikom/types/protos/avikom/generic\252\002\024Avikom.Generic.Types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x61vikom/generic/options.proto\x12\x0e\x61vikom.generic\x1a google/protobuf/descriptor.proto\"\x80\x01\n\x0c\x46ieldOptions\x12\r\n\x05index\x18\x01 \x01(\x08\x12\x0e\n\x06unique\x18\x02 \x01(\x08\x12\x0f\n\x07\x64\x65\x66\x61ult\x18\x03 \x01(\t\x12\r\n\x05match\x18\x04 \x01(\t\x12\x0b\n\x03min\x18\x05 \x01(\t\x12\x11\n\timmutable\x18\x06 \x01(\x08\x12\x11\n\tautoIndex\x18\x07 \x01(\x08:M\n\x06schema\x12\x1d.google.protobuf.FieldOptions\x18\xd1\x86\x03 \x01(\x0b\x32\x1c.avikom.generic.FieldOptions:<\n\x11schema_definition\x12\x1f.google.protobuf.MessageOptions\x18\xd1\x86\x03 \x01(\x08\x42VZ=gitlab.ub.uni-bielefeld.de/avikom/types/protos/avikom/generic\xaa\x02\x14\x41vikom.Generic.Typesb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


SCHEMA_FIELD_NUMBER = 50001
schema = _descriptor.FieldDescriptor(
  name='schema', full_name='avikom.generic.schema', index=0,
  number=50001, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
SCHEMA_DEFINITION_FIELD_NUMBER = 50001
schema_definition = _descriptor.FieldDescriptor(
  name='schema_definition', full_name='avikom.generic.schema_definition', index=1,
  number=50001, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)


_FIELDOPTIONS = _descriptor.Descriptor(
  name='FieldOptions',
  full_name='avikom.generic.FieldOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='avikom.generic.FieldOptions.index', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unique', full_name='avikom.generic.FieldOptions.unique', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='default', full_name='avikom.generic.FieldOptions.default', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='match', full_name='avikom.generic.FieldOptions.match', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min', full_name='avikom.generic.FieldOptions.min', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='immutable', full_name='avikom.generic.FieldOptions.immutable', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='autoIndex', full_name='avikom.generic.FieldOptions.autoIndex', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=211,
)

DESCRIPTOR.message_types_by_name['FieldOptions'] = _FIELDOPTIONS
DESCRIPTOR.extensions_by_name['schema'] = schema
DESCRIPTOR.extensions_by_name['schema_definition'] = schema_definition
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FieldOptions = _reflection.GeneratedProtocolMessageType('FieldOptions', (_message.Message,), {
  'DESCRIPTOR' : _FIELDOPTIONS,
  '__module__' : 'avikom.generic.options_pb2'
  # @@protoc_insertion_point(class_scope:avikom.generic.FieldOptions)
  })
_sym_db.RegisterMessage(FieldOptions)

schema.message_type = _FIELDOPTIONS
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(schema)
google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(schema_definition)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
